#!/bin/bash
#PBS -N kraken_tp3_23to44
#PBS -l nodes=1:ppn=12
#PBS -l vmem=95GB
#PBS -l walltime=24:00:00

start=$(date +%s)
set -o nounset
set -o errexit
module load jellyfish
module load kraken
FILES=/group/gibaslab/working_files/trimmed_reads/time_point_3/metagenome/*
OUT=/group/gibaslab/working_files/kraken_reports/tp3
KDB=/group/gibaslab/krakenDB
SUF=Set3
TEST_SETS=( {23..44} )
echo SCRIPT EXECUTING KRAKEN ON TEST SETS: ${TEST_SETS[@]}
for i in ${TEST_SETS[@]}
do
	testSet=$i$SUF
	fileR1=null
	fileR2=null
	for f in $FILES
	do
		if [[ $f == *-paired* && $f == *_$testSet* ]]; then
			if [[ $f == *R1* ]]; then
				echo $i R1 is $f
				fileR1=$f
			elif [[ $f == *R2* ]]; then
				echo $i R2 is $f
				fileR2=$f
			else
				echo ERROR - $F IS NOT A PAIRED FILE - MISSING R1/R2
			fi
		fi
	done
	if [[ $fileR1 != null && $fileR2 != null ]]; then
		kraken --gzip-compressed --fastq-input --DB $KDB --paired $fileR1 $fileR2 > $OUT/$testSet.txt
		kraken-report --DB $KDB $OUT/$testSet.txt > $OUT/$testSet.report.txt
		chmod 775 $OUT/$testSet.*
	fi
done
echo KRAKEN REPORTS CREATED FOR TEST SETS: ${TEST_SETS[@]}
end=$(date +%s)
runtime="$(($end - $start))"
echo SCRIPT COMPLETE: RUNTIME is $runtime seconds


















































































